### ISSUE TITLE
Nullref when serializing asset on Unity 2022

### ISSUE THREAD

**Issue by laicasaane** [elringus/sprite-dicing#39]
Unity 2022.3.14
SpriteDicing 1.10.0

I'm receiving this exception when trying tpo build the atlas.

```
Failed to build diced sprite atlas. System.ArgumentNullException: Value cannot be null.
Parameter name: _unity_self
  at (wrapper managed-to-native) UnityEditor.SerializedObject.ApplyModifiedProperties(UnityEditor.SerializedObject)
  at SpriteDicing.Editors.AtlasBuilder.<PackTextures>g__SaveAtlasTextures|8_2 (System.Collections.Generic.IReadOnlyList`1[T] textures) [0x0003d] in D:\Projects\SpriteDicing\Assets\SpriteDicing\Editor\Editors\AtlasBuilder.cs:106 
  at SpriteDicing.Editors.AtlasBuilder.PackTextures (System.Collections.Generic.IReadOnlyList`1[T] dicedTextures) [0x00068] in D:\Projects\SpriteDicing\Assets\SpriteDicing\Editor\Editors\AtlasBuilder.cs:77 
  at SpriteDicing.Editors.AtlasBuilder.Build () [0x0000f] in D:\Projects\SpriteDicing\Assets\SpriteDicing\Editor\Editors\AtlasBuilder.cs:32 
UnityEngine.Debug:LogError (object)
SpriteDicing.Editors.AtlasBuilder:Build () (at Assets/SpriteDicing/Editor/Editors/AtlasBuilder.cs:38)
SpriteDicing.Editors.DicedSpriteAtlasEditor:DrawInputFolderGUI () (at Assets/SpriteDicing/Editor/Editors/DicedSpriteAtlasEditor.cs:142)
SpriteDicing.Editors.DicedSpriteAtlasEditor:OnInspectorGUI () (at Assets/SpriteDicing/Editor/Editors/DicedSpriteAtlasEditor.cs:43)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Comment by elringus** [comment]
Probably a Unity regression as it's working fine on 2019.4.

**Comment by elringus** [comment]
Unity editor seem to dispose/invalidate serialized asset reference here: https://github.com/elringus/SpriteDicing/blob/master/Assets/SpriteDicing/Editor/Editors/DicedSpriteSerializer.cs#L111

This is most likely a regression on the Unity side, as it started happening in a 2022 release, while worked fine before w/o any changes on our side.

I'm not using 2022 myself; would appreciate if someone can send a bug report to Unity and/or have an idea of a workaround/temp fix.

**Comment by elringus** [comment]
I've traced it down to `AssetDatabase.SaveAssets()` call:

https://github.com/elringus/sprite-dicing/blob/365db9c695297fc2b35296cadbea21606d4401dd/Assets/SpriteDicing/Editor/Editors/DicedSpriteSerializer.cs#L81

Seems like invoking those causes Unity to dispose the editor. After removing all the "SaveAssets" in all the editors (except the last one at the end of build), it seems to work fine, until you change any property, at which point it fails again, but works when repeated. As a temp workaround (until the bug is fixed on the Unity side), try removing the save calls and build twice after changing atlas properties.
